version: '3'
services:
  php:
    # image: php:8-apache
    build:
      context: .
      dockerfile: Dockerfile
    
    volumes:
      - ./src:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - mysql
    # command: ["wait-for-it", "mysql:3306", "--", "apache2-foreground"]
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  mysql_data: